### ISSUE TITLE
`Kmail.send` breaks if messages include `&`

### ISSUE THREAD

**Issue by slifty** [loathers/libram#505]
The current implementation of `send` will inject the `message` directly (without encoding) when constructing the url to invoke the send.

This means if the message contains an ampersand that is interpreted as being part of the URL (and the rest of the message is treated as part of the URL).  This results in unexpected behavior and is a potential security vulnerability (e.g. if someone incorporates user input / quotes in the construction of the message).

The most correct solution is to `urlEncode` the message before constructing the query string -- however, `visitUrl()` also encodes each piece of the query string by default (which, left unaddressed, would result in a double encoding).   To prevent this we would need to call `visitUrl` and pass `false` to bypass its encoding.  We can't do *that* safely unless we manually encode all the other query string parameters as well.

The way `send` is currently written has various query string parameters that are built across a few different locations, through a [generic send function](https://github.com/loathers/libram/blob/87e39f18e455de51dec98cb14faee88e25eee8f7/src/Kmail.ts#L68-L118) that partially constructs parameters via a provided callback.  Being able to safely ensure that all parts of the URL are encoded properly might warrant a small internal refactor of that logic.

**Comment by oxc** [comment]
To be frank, the automagic encoding of visit_url was never a good idea, because of the very reasons outlined above. If one could reliably detect which parts need to be encoded, one would need no encoding at all.
I've proposed a libram wrapper to visitUrl in #549, I suppose it is more indigenous to JavaScript to just pass an object of query parameters than it might be in ASH.
